cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  
  - test
  - build

test:
  stage: test
  script:
    - echo "Running tests"
    - npm run test

build_prod:
  stage: build
  script:
    - echo "Building production package"
    - npm run build
    - echo "Publishing"
    - npm publish

  only:
  - master





